name: CI

on:
    release:
        types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup shc tool
      run: |
        apt-get update && apt-get install software-properties-common -y
        add-apt-repository ppa:neurobin/ppa -y
        apt-get update && apt-get install shc -y
    - name: Create new binary using script
      run: |
        rm -f l200labs_binaries/*
        bash shc_script_converter.sh
    - name: Login to DockerHub Registry
      run: echo $ | docker login -u $ --password-stdin
    - name: Get the version
      id: vars
      run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
    - name: Build the tagged Docker image
      run: docker build . --file Dockerfile --tag sturrent/l200labs:$
    - name: Push the tagged Docker image
      run: docker push sturrent/l200labs:$
    - name: Build the latest Docker image
      run: docker build . --file Dockerfile --tag sturrent/l200labs:latest
    - name: Push the latest Docker image
      run: docker push sturrent/l200labs:latest
    
